/* --------------------------------------------------------------------------
   DATA
   -------------------------------------------------------------------------- */
const DATA = {
   "attributes":{
      "Strength":["Acrobatics","Armorer","Axe","Blunt Weapon","Long Blade"],
      "Intelligence":["Alchemy","Conjuration","Enchant","Security"],
      "Willpower":["Alteration","Destruction","Mysticism","Restoration"],
      "Agility":["Block","Light Armor","Marksman","Sneak"],
      "Speed":["Athletics","Hand-to-hand","Short Blade","Unarmored"],
      "Endurance":["Heavy Armor","Medium Armor","Spear"],
      "Personality":["Illusion","Mercantile","Speechcraft"]},

   "races":{
      "Argonian":{
         "male":[40,40,30,50,50,30,30,40],
         "female":[40,50,40,40,40,30,30,40],
         "bonuses":{"Alchemy":5,"Athletics":15,"Illusion":5,"Medium Armor":5,"Mysticism":5,"Spear":5,"Unarmored":5},
         "traits":{"abilities":["Resist Poison 100%","Resist Common Disease 75%"],"powers":[],"spells":["Water Breathing for 120 seconds"]}},
      "Breton":{
         "male":[40,50,50,30,30,30,40,40],
         "female":[30,50,50,30,40,30,40,40],
         "bonuses":{"Alchemy":5,"Alteration":5,"Conjuration":10,"Illusion":5,"Mysticism":10,"Restoration":10},
         "traits":{"abilities":["Resist Magicka 50%","Maximum Magicka +0.5× Intelligence"],"powers":["Dragon Skin: Shield 50 pts for 60 seconds on Self"],"spells":[]}},
      "Dark Elf":{
         "male":[40,40,30,40,50,40,30,40],
         "female":[40,40,30,40,50,30,40,40],
         "bonuses":{"Athletics":5,"Destruction":5,"Light Armor":5,"Long Blade":5,"Marksman":5,"Mysticism":5,"Short Blade":5},
         "traits":{"abilities":["Resist Fire 75%"],"powers":["Ancestor Guardian: Sanctuary 50 pts for 60 seconds on Self"],"spells":[]}},
      "High Elf":{
         "male":[30,50,40,40,30,40,40,40],
         "female":[30,50,50,40,40,30,40,40],
         "bonuses":{"Alchemy":10,"Alteration":5,"Conjuration":5,"Destruction":10,"Enchant":10,"Illusion":5},
         "traits":{"abilities":["Resist Common Disease 75%","Weakness to Fire 50%","Weakness to Frost 25%","Weakness to Shock 25%","Weakness to Magicka 50%","Maximum Magicka +1.5× Intelligence"],"powers":[],"spells":[]}},
      "Imperial":{
         "male":[40,40,30,30,40,40,50,40],
         "female":[40,40,40,30,30,40,50,40],
         "bonuses":{"Blunt Weapon":5,"Hand-to-hand":5,"Light Armor":5,"Long Blade":10,"Mercantile":10,"Speechcraft":10},
         "traits":{"abilities":[],"powers":["Star of the West: Absorb Fatigue 200 pts on Touch","Voice of the Emperor: Charm 25–50 pts for 15 seconds on Target"],"spells":[]}},
      "Khajiit":{
         "male":[40,40,30,50,40,30,40,40],
         "female":[30,40,30,50,40,40,40,40],
         "bonuses":{"Acrobatics":15,"Athletics":5,"Hand-to-hand":5,"Light Armor":5,"Security":5,"Short Blade":5,"Sneak":5},
         "traits":{"abilities":[],"powers":["Eye of Fear: Demoralize Humanoid 100 pts for 30 seconds on Target"],"spells":["Eye of Night: Night Eye 50 pts for 30 seconds on Self"]}},
      "Nord":{
         "male":[50,30,40,30,40,50,30,40],
         "female":[50,30,50,30,40,40,30,40],
         "bonuses":{"Axe":10,"Blunt Weapon":10,"Heavy Armor":5,"Long Blade":5,"Medium Armor":10,"Spear":5},
         "traits":{"abilities":["Resist Shock 50%","Resist Frost 100%"],"powers":["Thunder Fist: Frost Damage 25 pts on Touch","Woad: Shield 30 pts for 60 seconds on Self"],"spells":[]}},
      "Orc":{
         "male":[45,30,50,35,30,50,30,40],
         "female":[45,40,45,35,30,50,25,40],
         "bonuses":{"Armorer":10,"Axe":5,"Block":10,"Heavy Armor":10,"Medium Armor":10},
         "traits":{"abilities":["Resist Magicka 25%"],"powers":["Berserk: Fortify Health 20 pts for 60 seconds on Self; Fortify Fatigue 200 pts for 60 seconds on Self; Fortify Attack 100 pts for 60 seconds on Self; Drain Agility 100 pts for 60 seconds on Self"],"spells":[]}},
      "Redguard":{
         "male":[50,30,30,40,40,50,30,40],
         "female":[40,30,30,40,40,50,40,40],
         "bonuses":{"Athletics":5,"Axe":5,"Blunt Weapon":5,"Heavy Armor":5,"Long Blade":15,"Medium Armor":5,"Short Blade":5},
         "traits":{"abilities":["Resist Common Disease 75%","Resist Poison 75%"],"powers":["Adrenaline Rush: Fortify Agility 50 pts, Strength 50 pts, Speed 50 pts, Endurance 50 pts, and Health 25 pts for 60 seconds on Self"],"spells":[]}},
      "Wood Elf":{
         "male":[30,40,30,50,50,30,40,40],
         "female":[30,40,30,50,50,30,40,40],
         "bonuses":{"Acrobatics":5,"Alchemy":5,"Light Armor":10,"Marksman":15,"Sneak":10},
         "traits":{"abilities":["Resist Common Disease 75%"],"powers":["Beast Tongue: Command Creature 5 levels for 600 seconds on Target"],"spells":[]}}},

   "trRaces":{
      "Ayleid":{
         "male":[30,60,40,40,40,30,40,30],
         "female":[30,60,40,40,40,30,40,30],
         "bonuses":{"Enchant":15,"Alteration":10,"Illusion":10,"Conjuration":5,"Mysticism":5},
         "traits":{"abilities":["Resist Shock: Resist Shock 50 pts on Self","Magicka Bonus: Fortify Maximum Magicka 1.0× Intelligence pts on Self"],"powers":["Light of Auri-El: Light 25 pts for 30 seconds on Self; Spell Absorption 10 pts for 30 seconds on Self; Restore Health 2 pts for 30 seconds on Self; Restore Magicka 5 pts for 30 seconds on Self"],"spells":["Light: Light 20 pts in 30ft for 30 seconds on Target"]}},
      "Cathay":{
         "male":[45,40,30,40,35,50,30,40],
         "female":[40,40,30,45,35,50,30,40],
         "bonuses":{"Athletics":10,"Short Blade":5,"Long Blade":5,"Light Armor":5,"Security":10,"Sneak":5,"Spear":5},
         "traits":{"abilities":["Vitality of Cathay: Fortify Attack 5 pts on Self; Fortify Health 10 pts on Self"],"powers":["Eye of Fear: Demoralize Humanoid 100 pts for 30 seconds on Target"],"spells":["Eye of Night: Night Eye 50 pts for 30 seconds on Self"]}},
      "Cathay-raht":{
         "male":[45,40,30,40,35,50,30,40],
         "female":[40,40,30,45,35,50,30,40],
         "bonuses":{"Athletics":15,"Long Blade":10,"Light Armor":10,"Short Blade":5,"Sneak":5},
         "traits":{"abilities":["Blood of Cathay-raht: Fortify Attack 5 pts on Self; Fortify Endurance 10 pts on Self; Fortify Strength 10 pts on Self"],"powers":["Eye of Fear: Demoralize Humanoid 100 pts for 30 seconds on Target"],"spells":["Eye of Night: Night Eye 50 pts for 30 seconds on Self"]}},
      "Chimeri-Quey":{
         "male":[45,40,35,30,30,40,50,40],
         "female":[40,40,35,30,30,40,55,40],
         "bonuses":{"Mercantile":10,"Speechcraft":10,"Mysticism":10,"Conjuration":5,"Acrobatics":5,"Axe":5},
         "traits":{"abilities":["Weakness to Blight Disease 25 pts on Self","Resist Magicka 15 pts on Self","Resist Shock 50 pts on Self"],"powers":["Sprit of Quey: Absorb Personality 25 pts for 30 seconds on Touch; Calm Humanoid 30 pts for 30 seconds on Touch","Ancestor Warden: Summon Ancestral Ghost for 60 seconds on Self"],"spells":[]}},
      "Dagi-raht":{
         "male":[30,40,50,50,50,25,25,40],
         "female":[25,40,50,50,50,25,30,40],
         "bonuses":{"Acrobatics":15,"Athletics":5,"Destruction":5,"Hand-to-hand":5,"Illusion":5,"Sneak":10},
         "traits":{"abilities":["Magicka Bonus: Fortify Maximum Magicka 0.5× Intelligence"],"powers":["Shadow Paw of Dagi-raht: Fortify Acrobatics 30 pts for 60 seconds on Self; Fortify Hand-to-hand 30 pts for 60 seconds on Self; Fortify Sneak 30 pts for 60 seconds on Self; Chameleon 30 pts for 60 seconds on Self"],"spells":["Tree-Dweller's Landing: Slowfall 15 pts for 10 seconds on Self","Eye of Night: Night Eye 50 pts for 30 seconds on Self"]}},
      "Duadri":{
         "male":[30,35,40,45,30,40,50,40],
         "female":[40,35,40,45,30,40,40,40],
         "bonuses":{"Acrobatics":10,"Athletics":5,"Light Armor":5,"Mercantile":5,"Mysticism":10,"Spear":5,"Unarmored":5},
         "traits":{"abilities":["Weakness to Shock 50 pts on Self"],"powers":["Cardinal Aptitude: Feather 50 pts for 60 seconds on Self; Sanctuary 30 pts for 60 seconds on Self; Fortify Luck 10 pts for 60 seconds on Self"],"spells":["Tava's Gale: Slowfall 20 pts for 10 seconds on Self"]}},
      "Hill Giant":{
         "male":[100,20,20,10,5,100,5,50],
         "female":[100,20,20,10,5,100,5,50],
         "bonuses":{"Blunt Weapon":25,"Hand-to-hand":15,"Unarmored":5},
         "traits":{"abilities":["Atmoran Blood: Restore Health 5 pts on Self; Restore Fatigue 10 pts on Self","Colossal Frame: Damage Speed 75 pts on Self; Fortify Endurance 250 pts on Self; Fortify Strength 250 pts on Self","Skin of Stone: Fortify Unarmored 100 pts on Self; Resist Frost 100 pts on Self; Resist Normal Weapons 100 pts on Self; Reflect 50 pts on Self"],"powers":[],"spells":[]}},
      "Imga":{
         "male":[55,40,35,40,30,30,40,40],
         "female":[55,40,35,40,30,30,40,40],
         "bonuses":{"Speechcraft":15,"Mysticism":10,"Hand-to-hand":10,"Acrobatics":5,"Mercantile":5},
         "traits":{"abilities":["Weakness to Poison 50 pts on Self","Resist Paralysis 50 pts on Self","Soul Branch: Detect Animal 60-80 pts on Self"],"powers":["Prophet's Denial: Sound 50 pts for 30 seconds on Target; Demoralize Humanoid 30 pts for 30 seconds on Target"],"spells":[]}},
      "Keptu-Quey":{
         "male":[45,35,40,30,30,50,40,40],
         "female":[40,35,40,30,35,45,45,40],
         "bonuses":{"Armorer":5,"Block":10,"Blunt Weapon":15,"Hand-to-hand":5,"Heavy Armor":5,"Unarmored":5},
         "traits":{"abilities":["Weakness to Blight Disease 25 pts on Self"],"powers":["Sprit of Quey: Absorb Personality 25 pts for 30 seconds on Touch; Calm Humanoid 30 pts for 30 seconds on Touch","Unbreakable: Fortify Block 100 pts for 60 seconds on Self; Resist Normal Weapons 50 pts for 60 seconds on Self; Drain Speed 50 pts for 60 seconds on Self"],"spells":[]}},
      "Malahk Orc":{
         "male":[55,25,45,40,25,60,20,40],
         "female":[50,30,45,40,25,60,20,40],
         "bonuses":{"Unarmored":5,"Axe":10,"Blunt Weapon":5,"Heavy Armor":10,"Medium Armor":10,"Hand-to-hand":5},
         "traits":{"abilities":["True Blood of Malahk: Fortify Attack 20 pts on Self; Resist Magicka 25 pts on Self; Resist Frost 50 pts on Self; Resist Paralysis 50 pts on Self"],"powers":["Berserk: Fortify Health 50 pts for 60 seconds on Self; Fortify Fatigue 100 pts for 60 seconds on Self; Fortify Attack 100 pts for 60 seconds on Self; Fortify Speed 50 pts for 60 seconds on Self; Drain Agility 100 pts for 60 seconds on Self"],"spells":[]}},
      "Naga":{
         "male":[45,40,30,40,40,45,30,40],
         "female":[45,40,30,40,40,45,30,40],
         "bonuses":{"Unarmored":15,"Blunt Weapon":5,"Alteration":5,"Hand-to-hand":5,"Athletics":5,"Sneak":5,"Restoration":5},
         "traits":{"abilities":["Swift Swim: Swift Swim 20 pts on Self"],"powers":["Stalker's Shroud: Chameleon 50 pts for 60 seconds on Target; Detect Animal 100 pts for 60 seconds on Self"],"spells":["Water Breathing: Water Breathing for 2 minutes on Self, Cost: 5"]}},
      "Ogre":{
         "male":[60,20,25,35,50,65,15,40],
         "female":[55,25,25,35,50,65,15,40],
         "bonuses":{"Hand-to-hand":10,"Axe":5,"Blunt Weapon":10,"Unarmored":15,"Spear":5},
         "traits":{"abilities":["Enduring Physique: Fortify Attack 10 pts on Self","Resist Normal Weapons 4-40 pts on Self"],"powers":["Savage Roar: Demoralize Creature 20 pts in 10ft for 15 seconds on Target; Demoralize Humanoid 20 pts in 10ft for 15 seconds on Target","Mouloch's Protection: Resist Magicka 50 pts for 30 seconds on Self; Sanctuary 50 pts for 30 seconds on Self"],"spells":[]}},
      "Ohmes":{
         "male":[35,40,30,50,40,30,45,40],
         "female":[30,40,30,50,40,35,45,40],
         "bonuses":{"Acrobatics":10,"Mercantile":5,"Speechcraft":10,"Light Armor":5,"Security":5,"Short Blade":5,"Sneak":5},
         "traits":{"abilities":["Tenacity of Ohmes: Resist Common Disease 25 pts on Self"],"powers":["Eye of Fear: Demoralize Humanoid 100 pts for 30 seconds on Target"],"spells":["Eye of Night: Night Eye 50 pts for 30 seconds on Self, Cost: 0"]}},
      "Ohmes-raht":{
         "male":[30,45,30,50,40,30,45,40],
         "female":[30,45,30,50,40,30,45,40],
         "bonuses":{"Acrobatics":15,"Illusion":5,"Speechcraft":5,"Light Armor":5,"Security":5,"Sneak":10},
         "traits":{"abilities":["Temerity: Resist Paralysis 25 pts on Self"],"powers":["Perfect Balance: Feather 50 pts for 5 minutes on Self; Fortify Personality 10 pts for 5 minutes on Self; Slowfall 30 pts for 5 minutes on Self"],"spells":["Eye of Night: Night Eye 50 pts for 30 seconds on Self, Cost: 0"]}},
      "Reachman":{
         "male":[40,45,50,40,35,35,25,40],
         "female":[35,50,50,40,40,30,25,40],
         "bonuses":{"Conjuration":10,"Destruction":10,"Alteration":5,"Alchemy":10,"Blunt Weapon":5,"Athletics":5},
         "traits":{"abilities":["Magicka Bonus: Fortify Maximum Magicka 0.5× Intelligence (50% more Magicka)","Resist Magicka: Resist Magicka 25 pts on Self"],"powers":["Witch Eye: Disintegrate Armor 50 pts on Target; Blind 50 pts for 10 seconds on Target; Absorb Magicka 10 pts on Target","Blood Chant: Fortify Attack 100 pts for 60 seconds on Self; Fortify Fatigue 150 pts for 60 seconds on Self; Drain Agility 40 pts for 60 seconds on Self"],"spells":[]}},
      "Riverfolk":{
         "male":[40,40,30,50,30,40,40,40],
         "female":[40,40,30,50,30,40,40,40],
         "bonuses":{"Block":15,"Hand-to-hand":5,"Long Blade":5,"Mercantile":5,"Athletics":10,"Marksman":5},
         "traits":{"abilities":["Resist Shock 50 pts on Self"],"powers":["Mirror: Fortify Fatigue 150 pts for 60 seconds on Self; Reflect 25 pts for 60 seconds on Self"],"spells":[]}},
      "Sea Elf":{
         "male":[40,40,50,40,30,40,30,40],
         "female":[40,40,50,40,30,40,30,40],
         "bonuses":{"Athletics":5,"Alteration":10,"Destruction":10,"Illusion":5,"Spear":5,"Sneak":5,"Unarmored":5},
         "traits":{"abilities":["Blessing of the Veil: Sanctuary 10 pts on Self","Blessing of Serpent God: Fortify Maximum Magicka 0.5× INT pts on Self; Resist Poison 20 pts on Self"],"powers":["Mist Shroud: Chameleon 50 pts for 30 seconds on Self"],"spells":[]}},
      "Suthay":{
         "male":[40,40,30,55,35,30,40,40],
         "female":[30,40,30,55,35,40,40,40],
         "bonuses":{"Acrobatics":15,"Hand-to-hand":5,"Light Armor":5,"Security":5,"Short Blade":5,"Sneak":10},
         "traits":{"abilities":[],"powers":["Grace of Suthay Khajiit: Fortify Agility 10 pts for 30 seconds on Self; Fortify Agility 10 pts for 30 seconds on Self","Eye of Fear: Demoralize Humanoid 100 pts for 30 seconds on Target"],"spells":["Eye of Night: Night Eye 50 pts for 30 seconds on Self, Cost: 0"]}},
      "Tojay":{
         "male":[40,35,50,30,40,45,30,40],
         "female":[40,35,50,30,40,45,30,40],
         "bonuses":{"Restoration":15,"Mysticism":10,"Blunt Weapon":10,"Unarmored":5,"Alchemy":5},
         "traits":{"abilities":["Careful Step: Fortify Acrobatics 5 pts on Self; Detect Enchantment 10 pts on Self"],"powers":["Mountain Fastness: Fortify Health 30 pts for 3 minutes on Self; Resist Shock 20 pts for 3 minutes on Self; Resist Frost 20 pts for 3 minutes on Self"],"spells":["Eye of Night: Night Eye 50 pts for 30 seconds on Self, Cost: 0","Wild Open: Open 1-100 pts on Touch, Cost: 15","Vigor: Fortify Fatigue 5-20 pts for 30 seconds on Self, Cost: 9"]}},
      "Tsaesci":{
         "male":[30,40,45,50,40,30,35,40],
         "female":[30,40,45,50,40,30,35,40],
         "bonuses":{"Long Blade":10,"Medium Armor":5,"Athletics":10,"Unarmored":15,"Speechcraft":5},
         "traits":{"abilities":["Immortal Endurance: Restore Health 0-1 pts on Self"],"powers":[],"spells":["Immortal Endurance: Restore Health 0-1 pts for 50 seconds on Self, Cost: 5","Immortal Restoration: Restore Agility 10-20 pts on Self; Restore Endurance 10-20 pts on Self; Restore Intelligence 10-20 pts on Self; Restore Luck 10-20 pts on Self; Restore Personality 10-20 pts on Self; Restore Speed 10-20 pts on Self; Restore Strength 10-20 pts on Self; Restore Willpower 10-20 pts on Self, Cost: 5"]}}},

   "classes":{
      "Acrobat":{"spec":"Stealth","maj":["Acrobatics","Athletics","Marksman","Sneak","Unarmored"],"min":["Speechcraft","Light Armor","Hand-to-hand","Alteration","Spear"],"fav":["Agility","Endurance"]},
      "Agent":{"spec":"Stealth","maj":["Speechcraft","Sneak","Acrobatics","Light Armor","Short Blade"],"min":["Mercantile","Illusion","Unarmored","Conjuration","Block"],"fav":["Personality","Agility"]},
      "Archer":{"spec":"Combat","maj":["Marksman","Long Blade","Block","Athletics","Light Armor"],"min":["Unarmored","Medium Armor","Sneak","Spear","Restoration"],"fav":["Agility","Strength"]},
      "Assassin":{"spec":"Stealth","maj":["Sneak","Marksman","Light Armor","Short Blade","Acrobatics"],"min":["Security","Athletics","Block","Long Blade","Alchemy"],"fav":["Speed","Intelligence"]},
      "Barbarian":{"spec":"Combat","maj":["Axe","Medium Armor","Blunt Weapon","Athletics","Block"],"min":["Acrobatics","Unarmored","Marksman","Light Armor","Armorer"],"fav":["Strength","Speed"]},
      "Bard":{"spec":"Stealth","maj":["Speechcraft","Alchemy","Acrobatics","Long Blade","Block"],"min":["Mercantile","Security","Enchant","Illusion","Medium Armor"],"fav":["Personality","Intelligence"]},
      "Battlemage":{"spec":"Magic","maj":["Alteration","Destruction","Conjuration","Axe","Heavy Armor"],"min":["Mysticism","Alchemy","Enchant","Long Blade","Marksman"],"fav":["Intelligence","Strength"]},
      "Crusader":{"spec":"Combat","maj":["Blunt Weapon","Long Blade","Destruction","Heavy Armor","Block"],"min":["Restoration","Alchemy","Medium Armor","Armorer","Hand-to-hand"],"fav":["Agility","Strength"]},
      "Healer":{"spec":"Magic","maj":["Restoration","Mysticism","Alteration","Hand-to-hand","Speechcraft"],"min":["Illusion","Blunt Weapon","Light Armor","Alchemy","Unarmored"],"fav":["Willpower","Personality"]},
      "Knight":{"spec":"Combat","maj":["Long Blade","Axe","Speechcraft","Heavy Armor","Block"],"min":["Restoration","Armorer","Enchant","Mercantile","Medium Armor"],"fav":["Strength","Personality"]},
      "Mage":{"spec":"Magic","maj":["Mysticism","Destruction","Alteration","Illusion","Restoration"],"min":["Enchant","Conjuration","Short Blade","Alchemy","Unarmored"],"fav":["Intelligence","Willpower"]},
      "Monk":{"spec":"Stealth","maj":["Hand-to-hand","Unarmored","Athletics","Acrobatics","Sneak"],"min":["Block","Blunt Weapon","Restoration","Marksman","Light Armor"],"fav":["Agility","Willpower"]},
      "Nightblade":{"spec":"Magic","maj":["Mysticism","Illusion","Alteration","Sneak","Short Blade"],"min":["Light Armor","Security","Marksman","Unarmored","Destruction"],"fav":["Willpower","Speed"]},
      "Pilgrim":{"spec":"Stealth","maj":["Speechcraft","Mercantile","Marksman","Restoration","Medium Armor"],"min":["Illusion","Alchemy","Block","Hand-to-hand","Short Blade"],"fav":["Personality","Endurance"]},
      "Rogue":{"spec":"Combat","maj":["Short Blade","Mercantile","Axe","Light Armor","Hand-to-hand"],"min":["Block","Long Blade","Athletics","Medium Armor","Speechcraft"],"fav":["Speed","Personality"]},
      "Scout":{"spec":"Combat","maj":["Sneak","Long Blade","Medium Armor","Athletics","Block"],"min":["Marksman","Unarmored","Light Armor","Alchemy","Alteration"],"fav":["Speed","Endurance"]},
      "Sorcerer":{"spec":"Magic","maj":["Enchant","Conjuration","Mysticism","Destruction","Alteration"],"min":["Illusion","Short Blade","Marksman","Medium Armor","Heavy Armor"],"fav":["Intelligence","Endurance"]},
      "Spellsword":{"spec":"Magic","maj":["Block","Restoration","Long Blade","Destruction","Alteration"],"min":["Blunt Weapon","Axe","Medium Armor","Enchant","Alchemy"],"fav":["Willpower","Endurance"]},
      "Thief":{"spec":"Stealth","maj":["Security","Sneak","Acrobatics","Light Armor","Short Blade"],"min":["Marksman","Athletics","Mercantile","Speechcraft","Hand-to-hand"],"fav":["Speed","Agility"]},
      "Warrior":{"spec":"Combat","maj":["Long Blade","Medium Armor","Heavy Armor","Athletics","Block"],"min":["Armorer","Blunt Weapon","Axe","Spear","Marksman"],"fav":["Strength","Endurance"]},
      "Witchhunter":{"spec":"Magic","maj":["Conjuration","Enchant","Alchemy","Light Armor","Marksman"],"min":["Unarmored","Mysticism","Sneak","Block","Blunt Weapon"],"fav":["Intelligence","Agility"]}},
   
   "npcClasses":{
      "Alchemist":{"spec":"Magic","maj":["Alchemy","Alteration","Conjuration","Enchant","Mysticism"],"min":["Unarmored","Speechcraft","Block","Blunt Weapon","Hand-to-hand"],"fav":["Intelligence","Luck"]},
      "Apothecary":{"spec":"Magic","maj":["Alchemy","Security","Mercantile","Blunt Weapon","Destruction"],"min":["Light Armor","Block","Enchant","Restoration","Speechcraft"],"fav":["Intelligence","Agility"]},
      "Bookseller":{"spec":"Stealth","maj":["Mercantile","Sneak","Security","Mysticism","Speechcraft"],"min":["Unarmored","Block","Blunt Weapon","Hand-to-hand","Light Armor"],"fav":["Intelligence","Personality"]},
      "Buoyant Armiger":{"spec":"Stealth","maj":["Marksman","Light Armor","Destruction","Short Blade","Sneak"],"min":["Restoration","Athletics","Block","Acrobatics","Speechcraft"],"fav":["Agility","Willpower"]},
      "Caravaner":{"spec":"Combat","maj":["Mercantile","Sneak","Security","Acrobatics","Speechcraft"],"min":["Unarmored","Block","Blunt Weapon","Hand-to-hand","Light Armor"],"fav":["Intelligence","Endurance"]},
      "Champion":{"spec":"Combat","maj":["Axe","Block","Medium Armor","Light Armor","Marksman"],"min":["Athletics","Restoration","Acrobatics","Sneak","Alteration"],"fav":["Strength","Speed"]},
      "Clothier":{"spec":"Stealth","maj":["Mercantile","Sneak","Security","Acrobatics","Speechcraft"],"min":["Unarmored","Block","Blunt Weapon","Hand-to-hand","Light Armor"],"fav":["Intelligence","Agility"]},
      "Commoner":{"spec":"Stealth","maj":["Hand-to-hand","Unarmored","Athletics","Speechcraft","Mercantile"],"min":["Security","Block","Short Blade","Sneak","Acrobatics"],"fav":["Personality","Endurance"]},
      "Dreamer":{"spec":"Stealth","maj":["Marksman","Light Armor","Blunt Weapon","Short Blade","Sneak"],"min":["Block","Acrobatics","Athletics","Security","Hand-to-hand"],"fav":["Agility","Speed"]},
      "Drillmaster":{"spec":"Combat","maj":["Block","Acrobatics","Unarmored","Athletics","Hand-to-hand"],"min":["Long Blade","Short Blade","Blunt Weapon","Axe","Spear"],"fav":["Agility","Intelligence"]},
      "Enchanter":{"spec":"Magic","maj":["Enchant","Blunt Weapon","Alchemy","Destruction","Unarmored"],"min":["Alteration","Illusion","Conjuration","Mysticism","Restoration"],"fav":["Intelligence","Willpower"]},
      "Enforcer":{"spec":"Stealth","maj":["Short Blade","Light Armor","Marksman","Sneak","Destruction"],"min":["Security","Athletics","Mercantile","Block","Alteration"],"fav":["Agility","Speed"]},
      "Farmer":{"spec":"Combat","maj":["Speechcraft","Blunt Weapon","Hand-to-hand","Athletics","Unarmored"],"min":["Mercantile","Light Armor","Short Blade","Spear","Acrobatics"],"fav":["Personality","Endurance"]},
      "Gondolier":{"spec":"Stealth","maj":["Mercantile","Speechcraft","Sneak","Hand-to-hand","Unarmored"],"min":["Security","Short Blade","Restoration","Block","Light Armor"],"fav":["Strength","Personality"]},
      "Guard":{"spec":"Combat","maj":["Long Blade","Blunt Weapon","Block","Heavy Armor","Medium Armor"],"min":["Athletics","Hand-to-hand","Speechcraft","Acrobatics","Security"],"fav":["Strength","Endurance"]},
      "Guild Guide":{"spec":"Magic","maj":["Mysticism","Restoration","Mercantile","Speechcraft","Sneak"],"min":["Conjuration","Enchant","Security","Short Blade","Unarmored"],"fav":["Intelligence","Willpower"]},
      "Herder":{"spec":"Stealth","maj":["Light Armor","Marksman","Spear","Restoration","Athletics"],"min":["Acrobatics","Block","Axe","Medium Armor","Sneak"],"fav":["Agility","Endurance"]},
      "Hunter":{"spec":"Stealth","maj":["Light Armor","Marksman","Short Blade","Sneak","Athletics"],"min":["Acrobatics","Block","Axe","Medium Armor","Restoration"],"fav":["Agility","Speed"]},
      "Mabrigash":{"spec":"Magic","maj":["Restoration","Destruction","Alteration","Block","Axe"],"min":["Unarmored","Speechcraft","Sneak","Mysticism","Athletics"],"fav":["Willpower","Endurance"]},
      "Master-at-Arms":{"spec":"Combat","maj":["Spear","Short Blade","Long Blade","Axe","Blunt Weapon"],"min":["Block","Heavy Armor","Light Armor","Medium Armor","Hand-to-hand"],"fav":["Strength","Endurance"]},
      "Merchant":{"spec":"Combat","maj":["Speechcraft","Mercantile","Restoration","Armorer","Security"],"min":["Light Armor","Unarmored","Blunt Weapon","Long Blade","Medium Armor"],"fav":["Intelligence","Personality"]},
      "Miner":{"spec":"Combat","maj":["Block","Blunt Weapon","Axe","Unarmored","Light Armor"],"min":["Hand-to-hand","Heavy Armor","Restoration","Armorer","Spear"],"fav":["Strength","Endurance"]},
      "Necromancer":{"spec":"Magic","maj":["Conjuration","Destruction","Illusion","Mysticism","Enchant"],"min":["Blunt Weapon","Acrobatics","Sneak","Unarmored","Alteration"],"fav":["Intelligence","Willpower"]},
      "Noble":{"spec":"Combat","maj":["Speechcraft","Mercantile","Short Blade","Security","Athletics"],"min":["Light Armor","Block","Restoration","Sneak","Acrobatics"],"fav":["Personality","Luck"]},
      "Ordinator":{"spec":"Combat","maj":["Blunt Weapon","Long Blade","Destruction","Heavy Armor","Block"],"min":["Restoration","Alchemy","Medium Armor","Acrobatics","Hand-to-hand"],"fav":["Willpower","Strength"]},
      "Ordinator Guard":{"spec":"Combat","maj":["Blunt Weapon","Long Blade","Destruction","Heavy Armor","Block"],"min":["Restoration","Security","Medium Armor","Acrobatics","Hand-to-hand"],"fav":["Willpower","Strength"]},
      "Pauper":{"spec":"Stealth","maj":["Sneak","Athletics","Unarmored","Speechcraft","Mercantile"],"min":["Short Blade","Block","Blunt Weapon","Hand-to-hand","Acrobatics"],"fav":["Luck","Willpower"]},
      "Pawnbroker":{"spec":"Stealth","maj":["Mercantile","Sneak","Security","Athletics","Speechcraft"],"min":["Unarmored","Block","Blunt Weapon","Hand-to-hand","Acrobatics"],"fav":["Intelligence","Luck"]},
      "Priest":{"spec":"Magic","maj":["Restoration","Mysticism","Alteration","Blunt Weapon","Unarmored"],"min":["Conjuration","Speechcraft","Light Armor","Alchemy","Destruction"],"fav":["Willpower","Personality"]},
      "Publican":{"spec":"Stealth","maj":["Speechcraft","Mercantile","Sneak","Light Armor","Security"],"min":["Block","Blunt Weapon","Hand-to-hand","Medium Armor","Spear"],"fav":["Personality","Intelligence"]},
      "Savant":{"spec":"Stealth","maj":["Speechcraft","Mercantile","Alchemy","Unarmored","Athletics"],"min":["Security","Block","Short Blade","Sneak","Acrobatics"],"fav":["Intelligence","Personality"]},
      "Sharpshooter":{"spec":"Combat","maj":["Marksman","Medium Armor","Destruction","Enchant","Sneak"],"min":["Restoration","Athletics","Security","Acrobatics","Speechcraft"],"fav":["Agility","Intelligence"]},
      "Shipmaster":{"spec":"Stealth","maj":["Mercantile","Speechcraft","Short Blade","Athletics","Sneak"],"min":["Block","Mysticism","Security","Unarmored","Light Armor"],"fav":["Intelligence","Personality"]},
      "Slave":{"spec":"Stealth","maj":["Sneak","Acrobatics","Athletics","Heavy Armor","Hand-to-hand"],"min":["Restoration","Block","Armorer","Mercantile","Speechcraft"],"fav":["Endurance","Luck"]},
      "Smith":{"spec":"Combat","maj":["Block","Blunt Weapon","Unarmored","Hand-to-hand","Armorer"],"min":["Axe","Heavy Armor","Light Armor","Long Blade","Medium Armor"],"fav":["Strength","Endurance"]},
      "Smuggler":{"spec":"Combat","maj":["Blunt Weapon","Sneak","Mercantile","Short Blade","Speechcraft"],"min":["Athletics","Axe","Hand-to-hand","Long Blade","Spear"],"fav":["Speed","Personality"]},
      "Trader":{"spec":"Combat","maj":["Mercantile","Sneak","Speechcraft","Mysticism","Security"],"min":["Unarmored","Block","Blunt Weapon","Hand-to-hand","Light Armor"],"fav":["Strength","Personality"]},
      "Warlock":{"spec":"Magic","maj":["Destruction","Illusion","Short Blade","Light Armor","Restoration"],"min":["Athletics","Speechcraft","Acrobatics","Alteration","Sneak"],"fav":["Luck","Willpower"]},
      "Wise Woman":{"spec":"Magic","maj":["Restoration","Mysticism","Alteration","Hand-to-hand","Speechcraft"],"min":["Illusion","Blunt Weapon","Light Armor","Alchemy","Unarmored"],"fav":["Willpower","Personality"]},
      "Witch":{"spec":"Magic","maj":["Mysticism","Illusion","Conjuration","Unarmored","Short Blade"],"min":["Light Armor","Speechcraft","Acrobatics","Alteration","Sneak"],"fav":["Luck","Willpower"]}},
   
   "trClasses":{
      "Artist":{"spec":"Combat","maj":["Alchemy","Blunt Weapon","Short Blade","Speechcraft","Security"],"min":["Alteration","Illusion","Mercantile","Hand-to-hand","Unarmored"],"fav":["Intelligence","Personality"]},
      "Astrologer":{"spec":"Magic","maj":["Mysticism","Mercantile","Speechcraft","Conjuration","Illusion"],"min":["Restoration","Unarmored","Enchant","Sneak","Alteration"],"fav":["Intelligence","Personality"]},
      "Baker":{"spec":"Stealth","maj":["Alchemy","Speechcraft","Mercantile","Sneak","Light Armor"],"min":["Block","Medium Armor","Spear","Hand-to-hand","Blunt Weapon"],"fav":["Personality","Intelligence"]},
      "Banker":{"spec":"Stealth","maj":["Speechcraft","Mercantile","Sneak","Illusion","Security"],"min":["Unarmored","Long Blade","Medium Armor","Short Blade","Light Armor"],"fav":["Intelligence","Personality"]},
      "Barrister":{"spec":"Stealth","maj":["Speechcraft","Mercantile","Security","Hand-to-hand","Unarmored"],"min":["Short Blade","Sneak","Acrobatics","Block","Illusion"],"fav":["Personality","Intelligence"]},
      "Broker":{"spec":"Stealth","maj":["Mercantile","Speechcraft","Security","Short Blade","Unarmored"],"min":["Hand-to-hand","Sneak","Athletics","Mysticism","Illusion"],"fav":["Intelligence","Luck"]},
      "Carpenter":{"spec":"Combat","maj":["Mercantile","Hand-to-hand","Blunt Weapon","Axe","Unarmored"],"min":["Acrobatics","Athletics","Short Blade","Block","Armorer"],"fav":["Strength","Endurance"]},
      "Cook":{"spec":"Combat","maj":["Alchemy","Short Blade","Mercantile","Hand-to-hand","Blunt Weapon"],"min":["Security","Restoration","Athletics","Sneak","Spear"],"fav":["Agility","Intelligence"]},
      "Courtesan":{"spec":"Stealth","maj":["Speechcraft","Mercantile","Athletics","Unarmored","Hand-to-hand"],"min":["Short Blade","Sneak","Restoration","Security","Acrobatics"],"fav":["Personality","Intelligence"]},
      "Dockworker":{"spec":"Stealth","maj":["Athletics","Hand-to-hand","Blunt Weapon","Mercantile","Unarmored"],"min":["Block","Speechcraft","Short Blade","Acrobatics","Light Armor"],"fav":["Strength","Endurance"]},
      "Fisherman":{"spec":"Stealth","maj":["Spear","Athletics","Hand-to-hand","Short Blade","Unarmored"],"min":["Light Armor","Mercantile","Block","Acrobatics","Speechcraft"],"fav":["Strength","Endurance"]},
      "Fletcher":{"spec":"Stealth","maj":["Mercantile","Unarmored","Marksman","Short Blade","Light Armor"],"min":["Hand-to-hand","Acrobatics","Medium Armor","Armorer","Sneak"],"fav":["Agility","Personality"]},
      "Jeweler":{"spec":"Stealth","maj":["Mercantile","Unarmored","Hand-to-hand","Short Blade","Speechcraft"],"min":["Illusion","Enchant","Alchemy","Armorer","Security"],"fav":["Personality","Intelligence"]},
      "Lamp Knight":{"spec":"Combat","maj":["Heavy Armor","Blunt Weapon","Enchant","Block","Restoration"],"min":["Alteration","Medium Armor","Athletics","Long Blade","Armorer"],"fav":["Strength","Willpower"]},
      "Miner":{"spec":"Combat","maj":["Armorer","Block","Axe","Blunt Weapon","Unarmored"],"min":["Long Blade","Spear","Light Armor","Hand-to-hand","Heavy Armor"],"fav":["Strength","Endurance"]},
      "Naturalist":{"spec":"Magic","maj":["Alchemy","Alteration","Mercantile","Restoration","Enchant"],"min":["Short Blade","Athletics","Security","Unarmored","Blunt Weapon"],"fav":["Intelligence","Agility"]},
      "Potter":{"spec":"Stealth","maj":["Mercantile","Unarmored","Hand-to-hand","Short Blade","Athletics"],"min":["Alchemy","Speechcraft","Blunt Weapon","Acrobatics","Armorer"],"fav":["Personality","Endurance"]},
      "Ratcatcher":{"spec":"Stealth","maj":["Spear","Light Armor","Alchemy","Sneak","Block"],"min":["Short Blade","Security","Unarmored","Acrobatics","Hand-to-hand"],"fav":["Agility","Speed"]},
      "Sailor":{"spec":"Combat","maj":["Athletics","Hand-to-hand","Light Armor","Long Blade","Unarmored"],"min":["Acrobatics","Short Blade","Speechcraft","Mercantile","Axe"],"fav":["Strength","Agility"]},
      "Scribe":{"spec":"Stealth","maj":["Speechcraft","Unarmored","Alchemy","Mercantile","Restoration"],"min":["Security","Axe","Spear","Athletics","Enchant"],"fav":["Intelligence","Endurance"]},
      "Cat-catcher":{"spec":"Stealth","maj":["Blunt Weapon","Hand-to-hand","Athletics","Speechcraft","Sneak"],"min":["Security","Acrobatics","Light Armor","Marksman","Restoration"],"fav":["Agility","Personality"]},
      "Therionaut":{"spec":"Stealth","maj":["Acrobatics","Athletics","Mercantile","Security","Speechcraft"],"min":["Block","Light Armor","Unarmored","Hand-to-hand","Blunt Weapon"],"fav":["Intelligence","Personality"]},
      "Clever-Man":{"spec":"Magic","maj":["Destruction","Restoration","Alteration","Illusion","Conjuration"],"min":["Axe","Heavy Armor","Enchant","Mysticism","Block"],"fav":["Willpower","Intelligence"]}},
   

   "birthsigns":{
      "The Apprentice":{"description":"Maximum Magicka 1.5× Intelligence; Weakness to Magicka 50.","traits":{"abilities":["Elfborn: Maximum Magicka +1.5× Intelligence","Weakness to Magicka 50%"],"powers":[],"spells":[]},"month":"Sun's Height"},
      "The Atronach":{"description":"Maximum Magicka 2.0× Intelligence; Spell Absorption 50; Stunted Magicka.","traits":{"abilities":["Wombburn: Maximum Magicka +2× Intelligence","Spell Absorption 50%","Stunted Magicka"],"powers":[],"spells":[]},"month":"Sun's Dusk"},
      "The Lady":{"description":"Fortify Personality 25; Fortify Endurance 25.","traits":{"abilities":["Lady's Favor: Personality +25","Lady's Grace: Endurance +25"],"powers":[],"spells":[]},"month":"Hearthfire"},
      "The Lord":{"description":"Weakness to Fire 100; Blood of the North.","traits":{"abilities":["Trollkin: Weakness to Fire 100%"],"powers":[],"spells":["Blood of the North: Restore Health 2 pts for 30 seconds on Self"]},"month":"First Seed"},
      "The Lover":{"description":"Fortify Agility 25; Lover's Kiss.","traits":{"abilities":["Mooncalf: Agility +25"],"powers":["Lover's Kiss: Paralyze for 60 seconds on Target; Damage Fatigue 200 pts on Self"],"spells":[]},"month":"Sun's Dawn"},
      "The Mage":{"description":"Maximum Magicka 0.5× Intelligence.","traits":{"abilities":["Fay: Maximum Magicka +0.5× Intelligence"],"powers":[],"spells":[]},"month":"Rain's Hand"},
      "The Ritual":{"description":"Mara's Gift; Blessed Word; Blessed Touch.","traits":{"abilities":[],"powers":["Mara's Gift: Restore Health 100 pts on Self"],"spells":["Blessed Word: Turn Undead 100 pts for 30 seconds on Target","Blessed Touch: Turn Undead 100 pts for 30 seconds on Touch"]},"month":"Morning Star"},
      "The Serpent":{"description":"Star-Curse.","traits":{"abilities":[],"powers":[],"spells":["Star-Curse: Poison 3 pts for 30 seconds on Touch; Damage Health 1 pt for 30 seconds on Self"]}},
      "The Shadow":{"description":"Moonshadow.","traits":{"abilities":[],"powers":["Moonshadow: Invisibility for 60 seconds on Self"],"spells":[]},"month":"Second Seed"},
      "The Steed":{"description":"Fortify Speed 25.","traits":{"abilities":["Charioteer: Speed +25"],"powers":[],"spells":[]},"month":"Mid Year"},
      "The Thief":{"description":"Sanctuary 10.","traits":{"abilities":["Akaviri Danger-sense: Sanctuary 10 pts"],"powers":[],"spells":[]},"month":"Evening Star"},
      "The Tower":{"description":"Tower Key; Beggar's Nose.","traits":{"abilities":[],"powers":["Tower Key: Open 50 pts on Touch"],"spells":["Beggar's Nose: Detect Animal, Enchantment and Key within 200 ft for 60 seconds"]},"month":"Frostfall"},
      "The Warrior":{"description":"Fortify Attack 10.","traits":{"abilities":["Warwyrd: Fortify Attack 10 pts"],"powers":[],"spells":[]},"month":"Last Seed"}},
   
   "starterSpells":[
      {"name":"Sanctuary","skill":"Illusion","cost":15,"desc":"Sanctuary 10 pts for 30 seconds on Self","threshold":65},
      {"name":"Chameleon","skill":"Illusion","cost":15,"desc":"Chameleon 10 pts for 30 seconds on Self","threshold":65},
      {"name":"Bound Dagger","skill":"Conjuration","cost":6,"desc":"Bound Dagger for 60 seconds on Self","threshold":56},
      {"name":"Summon Ancestral Ghost","skill":"Conjuration","cost":21,"desc":"Summon Ancestral Ghost for 60 seconds on Self","threshold":71},
      {"name":"Water Walking","skill":"Alteration","cost":9,"desc":"Water Walking for 60 seconds on Self","threshold":59},
      {"name":"Shield","skill":"Alteration","cost":15,"desc":"Shield 5 pts for 30 seconds on Self","threshold":65},
      {"name":"Fire Bite","skill":"Destruction","cost":6,"desc":"Fire Damage 15-30 pts for 1 second on Touch","threshold":56},
      {"name":"Exhausting Touch","skill":"Destruction","cost":75,"desc":"Drain Fatigue 5-20 pts for 60 seconds on Touch","threshold":125,"unobtainable":true},
      {"name":"Detect Creature","skill":"Mysticism","cost":19,"desc":"Detect Animal 50-150 pts for 5 seconds on Self","threshold":69},
      {"name":"Tap Energy","skill":"Mysticism","cost":180,"desc":"Absorb Fatigue 20 pts for 30 seconds on Target","threshold":230,"unobtainable":true},
      {"name":"Hearth Heal","skill":"Restoration","cost":13,"desc":"Restore Health 20-80 pts on Self","threshold":63},
      {"name":"Feet of Notorgo","skill":"Restoration","cost":45,"desc":"Fortify Speed 10 pts for 90 seconds on Self","threshold":95,"unobtainable":true}],
   
   "factions":{
      "Fighters Guild":["Armorer","Axe","Block","Blunt Weapon","Heavy Armor","Long Blade"],
      "Mages Guild":["Alchemy","Alteration","Destruction","Enchant","Illusion","Mysticism"],
      "Thieves Guild":["Acrobatics","Light Armor","Marksman","Security","Short Blade","Sneak"],
      "Imperial Legion":["Athletics","Spear","Long Blade","Blunt Weapon","Heavy Armor","Block"],
      "Tribunal Temple":["Alchemy","Blunt Weapon","Conjuration","Mysticism","Restoration","Unarmored"],
      "Morag Tong":["Acrobatics","Illusion","Marksman","Light Armor","Short Blade","Sneak"],
      "House Hlaalu":["Light Armor","Marksman","Mercantile","Security","Short Blade","Speechcraft"],
      "House Redoran":["Armorer","Athletics","Heavy Armor","Long Blade","Medium Armor","Spear"],
      "House Telvanni":["Alteration","Conjuration","Destruction","Enchant","Illusion","Mysticism"],
      "Imperial Cult":["Speechcraft","Unarmored","Restoration","Mysticism","Conjuration","Enchant","Blunt Weapon"]},
   
   "rngClassNames":["Custom Class","Wanderer","Freelance Battlemage","Road Scholar","Odd Job Specialist","Independent Adventurer","Unlicensed Professional"],   
   "skills":["Block","Armorer","Medium Armor","Heavy Armor","Blunt Weapon","Long Blade","Axe","Spear","Athletics","Enchant","Destruction","Alteration","Illusion","Conjuration","Mysticism","Restoration","Alchemy","Unarmored","Security","Sneak","Acrobatics","Light Armor","Short Blade","Marksman","Mercantile","Speechcraft","Hand-to-hand"],
   "calendar":{"monthDays":{"Morning Star":30,"Sun's Dawn":28,"First Seed":31,"Rain's Hand":30,"Second Seed":31,"Mid Year":30,"Sun's Height":31,"Last Seed":31,"Hearthfire":30,"Frostfall":30,"Sun's Dusk":31,"Evening Star":31}}
};
